"""Add Reaction model

Revision ID: 52e7dadcd14f
Revises: b44577318daf
Create Date: 2026-04-08 18:11:09.259828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52e7dadcd14f'
down_revision = 'b44577318daf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('prayer_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prayer_id'], ['prayers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'prayer_id', name='unique_user_prayer_reaction')
    )
    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reactions_prayer_id'), ['prayer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reactions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_reactions_prayer_id'))

    op.drop_table('reactions')
    # ### end Alembic commands ###
