"""Add notification preference columns to users

Revision ID: 7160ae6d59bb
Revises: 52e7dadcd14f
Create Date: 2026-04-08 19:04:33.906380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7160ae6d59bb'
down_revision = '52e7dadcd14f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notifications_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('prayer_reminders_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reminder_minutes_before', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('missed_prayer_alerts', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('friend_activity_alerts', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('friend_activity_alerts')
        batch_op.drop_column('missed_prayer_alerts')
        batch_op.drop_column('reminder_minutes_before')
        batch_op.drop_column('prayer_reminders_enabled')
        batch_op.drop_column('notifications_enabled')

    # ### end Alembic commands ###
