"""Add Prayer model

Revision ID: 7a4667058a24
Revises: 56e8beefcc8a
Create Date: 2026-04-07 17:01:34.930089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a4667058a24'
down_revision = '56e8beefcc8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prayers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('prayer_name', sa.String(length=20), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('prayer_date', sa.Date(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prayers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prayers_prayer_date'), ['prayer_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_prayers_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prayers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prayers_user_id'))
        batch_op.drop_index(batch_op.f('ix_prayers_prayer_date'))

    op.drop_table('prayers')
    # ### end Alembic commands ###
